[MNT] Added post-merge hook and updated scripts
neurobagel/query-tool pull request #38
Opened 2024-02-29 17:53 UTC by Sauradip07

- fixes #43 
Changes proposed in this pull request:

- Added post-merge hook: This is a common practice in many JavaScript projects to automatically update dependencies after changes to the package.json file.

- Added type check support in pre-commit hook.

## Checklist

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [x] Tests pass
- [x] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

2024-02-29 20:09 UTC, rmanaem reviewed
Thanks for the PR @Sauradip07!
Please open an issue and describe why the proposed changes are required/beneficial.
We can then proceed with the review once the issue is linked here.

2024-03-01 09:12 UTC, Sauradip07 commented
> Thanks for the PR @Sauradip07! Please open an issue and describe why the proposed changes are required/beneficial. We can then proceed with the review once the issue is linked here.

Please Check

2024-03-05 01:01 UTC, rmanaem requested changes
Thanks for drafting the issue!
I've requested some changes following our discussion on #43, please take a look.

2024-03-05 01:01 UTC, rmanaem commented on .husky/post-merge
> +git diff HEAD^ HEAD --exit-code -- ./package.json || npm install
I think a clean install would be better here, see https://docs.npmjs.com/cli/v10/commands/npm-ci

2024-03-05 01:01 UTC, rmanaem commented on .husky/pre-commit
> +npm run typecheck
As mentioned in our discussion on #43 I think type check is unnecessary here as we have configured ESLint with appropriate plugins and rules to take care of this.

2024-03-05 01:01 UTC, rmanaem commented on package.json
> +    "format:check": "prettier --check .",
Nice!

2024-03-05 01:01 UTC, rmanaem commented on package.json
> +    "typecheck": "tsc --project tsconfig.json --noEmit",
We can also remove this.

2024-03-05 01:01 UTC, rmanaem commented on .lintstagedrc.json
> +  "*.{ts,tsx}": ["npm run lint:check", "npm run format:fix"]
Let's use the `format:check` for `prettier` here as well.

2024-03-05 17:40 UTC, rmanaem requested changes
Thanks for implementing changes!
There is one more thing left and after that this PR should be ready to merge.
I'd also suggest updating the title to something like `[MNT] Added post-merge hook and updated scripts` since the PR no longer includes integration of type check support.

2024-03-05 17:40 UTC, rmanaem commented on .lintstagedrc.json
> +  "*.{ts,tsx}": ["npm run lint:check", "npm run format:fix", "npm run format:check"]
I think we can remove the `npm run format:fix` now that we have the `npm run format:check`.

2024-03-05 21:36 UTC, rmanaem approved these changes
I believe this is ready to merge 🧑‍🍳

2024-03-05 21:37 UTC, merged

2024-03-07 18:27 UTC, surchs commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v0.1.0`](https://github.com/neurobagel/query-tool/releases/tag/v0.1.0) :rocket: