[ENH]  Implement Prettier CI Check for Code Consistency
neurobagel/query-tool pull request #44
Opened 2024-03-01 12:31 UTC by samadpls

- Closes #15 

Changes proposed in this pull request:

- Implement Prettier CI Check for Code Consistency

## Checklist

- [X] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [X] PR links to GitHub issue with mention `Closes #XXXX`
- [X] Tests pass
- [X] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

2024-03-01 20:42 UTC, rmanaem requested changes
Thanks for the PR @samadpls!
Please see the requested changes 🍒

2024-03-01 20:42 UTC, rmanaem commented on .github/workflows/prettier-ci.yaml
> +on:
I think it's a good idea to update the trigger events to include push to `main` and manual i.e.,

```
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  ```
  We've had issues with CIs passing on PR and breaking right after they were merged into `main` and it's nice to have the ability to trigger the workflow manually should the need ever arises.

2024-03-01 20:42 UTC, rmanaem commented on .github/workflows/prettier-ci.yaml
> +    paths:
I don't think this `path` here does anything since `prettier` is running on the entire repo if that's the case we can remove it.

2024-03-01 22:11 UTC, rmanaem reviewed
Thanks for implementing the requested changes!
One last thing, what do you think about renaming the `Prettier CI` to `prettier` and the config file from `prettier-ci.yaml` to `prettier.yaml`?

2024-03-04 15:25 UTC, rmanaem approved these changes
Thanks @samadpls for implementing the changes! 🧑‍🍳

2024-03-04 15:25 UTC, merged

2024-03-07 18:28 UTC, surchs commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v0.1.0`](https://github.com/neurobagel/query-tool/releases/tag/v0.1.0) :rocket: