[ENH]  Added `FormControlLabel` for clickable checkbox text
neurobagel/query-tool pull request #63
Opened 2024-03-08 17:20 UTC by samadpls

- Closes #58 

Changes proposed in this pull request:

- Added `FormControlLabel` for clickable checkbox text

## Checklist

_This section is for the PR reviewer_

- [X] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [ ] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [X] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:

- [ ] Tests have been added

For bug fixes:

- [ ] There is at least one test that would fail under the original bug conditions.

2024-03-13 20:37 UTC, surchs requested changes
Thanks @samadpls for the PR - but I think we need to talk a bit more about what the goal is here. We don't want to add a new label just to make the checkbox work. Maybe @rmanaem has some ideas here as well. But the main goal from a user perspective is "I can click outside the checkbox and the checkbox will still become checked". That can be achieved in a number of ways. Maybe you have some ideas?

2024-03-13 20:37 UTC, surchs commented on CHANGELOG.md
> +- [CI] Implement Prettier CI Check for Code Consistency [#44](https://github.com/neurobagel/query-tool/pull/44) ([@samadpls](https://github.com/samadpls))
This is an autogenerated file. Could you please roll this back - I added it to the prettierignore file in #83

2024-03-13 20:37 UTC, surchs commented on src/components/ResultCard.tsx
> +              label={datasetName}
This is a nice fix, but we don't want to add a label next to the checkbox, especially not with the `datasetName` that you can already see on the dataset card. So I think we need to talk a bit more about what to do here. From a UX perspective, the nicest thing might be to make the entire card element clickable to set and unset the checkbox.

2024-03-19 22:57 UTC, surchs commented
@samadpls would you like to either discuss or propose a solution here without adding a new label to the checkbox? Essentially without this:
![image](https://github.com/neurobagel/query-tool/assets/1302022/a20954cb-9aab-4b9d-96e4-0d2aa947244d)

2024-03-20 15:03 UTC, samadpls commented
> @samadpls would you like to either discuss or propose a solution here without adding a new label to the checkbox? Essentially without this:
> ![image](https://github.com/neurobagel/query-tool/assets/1302022/a20954cb-9aab-4b9d-96e4-0d2aa947244d)

I agree with your suggestion to avoid adding a new label to the checkbox. Perhaps we can add an `onClick` event to the Card component or explore other options you recommend.

2024-04-09 18:21 UTC, rmanaem commented
> I agree with your suggestion to avoid adding a new label to the checkbox. Perhaps we can add an onClick event to the Card component or explore other options you recommend.

Let's try the `onClick` event and explore other solutions if that doesn't work out as expected.

2024-05-09 19:12 UTC, samadpls commented
Apologies for any inconvenience caused. Due to time constraints, I won't be able to follow up on this specific PR.😢
However, It was a great experience working with all of you during the GSoC selection process!😊

2024-05-09 19:12 UTC, closed without merging

2024-05-09 19:36 UTC, rmanaem commented
@samadpls
No problem, It's understandable. Thanks for contributing to the project! 
Please stay in touch and feel welcome to contribute again to our repos!