[MNT] Add dependabot.yml
neurobagel/query-tool pull request #94
Opened 2024-03-22 04:45 UTC by Sauradip07

- Closes #90 

Changes proposed in this pull request:

- Added ` dependabot.yml ` for  automatically check and updates to dependencies

## Checklist

_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [ ] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass

For new features:

- [ ] Tests have been added

For bug fixes:

- [ ] There is at least one test that would fail under the original bug conditions.

2024-04-03 00:13 UTC, rmanaem requested changes
Thanks for the PR @Sauradip07!
Please see the requested change.

2024-04-03 00:13 UTC, rmanaem commented on .github/dependabot.yml
> +        update-types: ['version-update:semver-major']
We'd like to get updates for these dependencies so let's remove the `ignore`.

2024-04-03 17:11 UTC, rmanaem approved these changes
🧑‍🍳

2024-04-03 17:12 UTC, merged

2024-04-11 19:49 UTC, surchs commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v0.2.0`](https://github.com/neurobagel/query-tool/releases/tag/v0.2.0) :rocket: